// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtuhF5urPItCASHLR4evu_yZqpzKjckoE',
    appId: '1:831783546590:web:c93afa607a42241de39c4f',
    messagingSenderId: '831783546590',
    projectId: 'buyer-vendor-app',
    authDomain: 'buyer-vendor-app.firebaseapp.com',
    storageBucket: 'buyer-vendor-app.appspot.com',
    measurementId: 'G-L00M6FGVQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM5fTjQtYmHwkuzeV-tO2w2XJOL-2Bo5A',
    appId: '1:831783546590:android:68e3418475b9af96e39c4f',
    messagingSenderId: '831783546590',
    projectId: 'buyer-vendor-app',
    storageBucket: 'buyer-vendor-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDML30RWMvjqpMfZSOufiZN8jOSbJ-Sivk',
    appId: '1:831783546590:ios:062250dce8cdcc6de39c4f',
    messagingSenderId: '831783546590',
    projectId: 'buyer-vendor-app',
    storageBucket: 'buyer-vendor-app.appspot.com',
    iosBundleId: 'com.example.buyerVendorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDML30RWMvjqpMfZSOufiZN8jOSbJ-Sivk',
    appId: '1:831783546590:ios:04b2b9d6c0b5ae37e39c4f',
    messagingSenderId: '831783546590',
    projectId: 'buyer-vendor-app',
    storageBucket: 'buyer-vendor-app.appspot.com',
    iosBundleId: 'com.example.buyerVendorApp.RunnerTests',
  );
}
